# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import logo
from PyQt5.QtCore import QTime, QTimer
from datetime import datetime
import mysql.connector as mc


class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.setFixedHeight(800)
        AdminWindow.setFixedWidth(1200)
        AdminWindow.setGeometry(QtCore.QRect(85, 25, 1200, 800))
        AdminWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(AdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header1 = QtWidgets.QLabel(self.centralwidget)
        self.header1.setGeometry(QtCore.QRect(250, 10, 941, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.header1.setFont(font)
        self.header1.setAlignment(QtCore.Qt.AlignCenter)
        self.header1.setObjectName("header1")
        self.header2 = QtWidgets.QLabel(self.centralwidget)
        self.header2.setGeometry(QtCore.QRect(390, 70, 631, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.header2.setFont(font)
        self.header2.setAlignment(QtCore.Qt.AlignCenter)
        self.header2.setObjectName("header2")
        self.background1 = QtWidgets.QLabel(self.centralwidget)
        self.background1.setGeometry(QtCore.QRect(0, 170, 1200, 581))
        self.background1.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.background1.setText("")
        self.background1.setObjectName("background1")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 231, 151))
        self.logo.setStyleSheet("image: url(:/logo/logo.png);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.klogin = QtWidgets.QLabel(self.centralwidget)
        self.klogin.setGeometry(QtCore.QRect(10, 170, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.klogin.setFont(font)
        self.klogin.setObjectName("klogin")
        self.waktu = QtWidgets.QLabel(self.centralwidget)
        self.waktu.setGeometry(QtCore.QRect(890, 170, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.waktu.setFont(font)
        self.waktu.setAlignment(QtCore.Qt.AlignCenter)
        self.waktu.setObjectName("waktu")
        self.keterangan = QtWidgets.QLabel(self.centralwidget)
        self.keterangan.setGeometry(QtCore.QRect(454, 170, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.keterangan.setFont(font)
        self.keterangan.setStyleSheet("background-color: rgb(99, 99, 99);\n"
                                      "color: white;\n"
                                      "")
        self.keterangan.setAlignment(QtCore.Qt.AlignCenter)
        self.keterangan.setObjectName("keterangan")
        self.tpelanggan = QtWidgets.QTableWidget(self.centralwidget)
        self.tpelanggan.setGeometry(QtCore.QRect(10, 260, 1181, 421))
        self.tpelanggan.setObjectName("tpelanggan")
        self.tpelanggan.setColumnCount(0)
        self.tpelanggan.setRowCount(0)
        self.bhapus = QtWidgets.QPushButton(self.centralwidget)
        self.bhapus.setGeometry(QtCore.QRect(690, 690, 191, 41))
        self.bhapus.clicked.connect(self.deletepelanggan)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bhapus.setFont(font)
        self.bhapus.setObjectName("bhapus")
        self.breload = QtWidgets.QPushButton(self.centralwidget)
        self.breload.setGeometry(QtCore.QRect(10, 210, 191, 41))
        self.breload.clicked.connect(self.readpelanggan)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.breload.setFont(font)
        self.breload.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.breload.setObjectName("breload")
        self.lidpel = QtWidgets.QLineEdit(self.centralwidget)
        self.lidpel.setGeometry(QtCore.QRect(370, 690, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lidpel.setFont(font)
        self.lidpel.setText("")
        self.lidpel.setAlignment(QtCore.Qt.AlignCenter)
        self.lidpel.setObjectName("lidpel")
        self.lketerangan = QtWidgets.QLabel(self.centralwidget)
        self.lketerangan.setGeometry(QtCore.QRect(520, 230, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lketerangan.setFont(font)
        self.lketerangan.setStyleSheet("background-color: rgb(206, 206, 206);\n"
                                       "color: rgb(255, 0, 0);")
        self.lketerangan.setObjectName("lketerangan")
        AdminWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AdminWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        AdminWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AdminWindow)
        self.statusbar.setObjectName("statusbar")
        AdminWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AdminWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

        self.tpelanggan.setColumnCount(7)
        self.tpelanggan.setHorizontalHeaderItem(
            0, QtWidgets.QTableWidgetItem("ID"))
        self.tpelanggan.setHorizontalHeaderItem(
            1, QtWidgets.QTableWidgetItem("Status"))
        self.tpelanggan.setHorizontalHeaderItem(
            2, QtWidgets.QTableWidgetItem("Jenis"))
        self.tpelanggan.setHorizontalHeaderItem(
            3, QtWidgets.QTableWidgetItem("Plat Nomor"))
        self.tpelanggan.setHorizontalHeaderItem(
            4, QtWidgets.QTableWidgetItem("Jam"))
        self.tpelanggan.setHorizontalHeaderItem(
            5, QtWidgets.QTableWidgetItem("Tanggal"))
        self.tpelanggan.setHorizontalHeaderItem(
            6, QtWidgets.QTableWidgetItem("Biaya"))

        for no in range(7):
            self.tpelanggan.setColumnWidth(no, 161)

        self.timer = QTimer()
        self.timer.timeout.connect(self.timing)
        self.timer.start(1000)

        self.timing()
        self.koneksi()

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "ADMINISTRATOR"))
        self.header1.setText(_translate(
            "AdminWindow", "OPERATOR PAS MASUK PELABUHAN"))
        self.header2.setText(_translate("AdminWindow", "UPP KELAS III SAPUDI"))
        self.klogin.setText(_translate("AdminWindow", "ADMIN"))
        self.keterangan.setText(_translate(
            "AdminWindow", "HALAMAN ADMINISTRATOR"))
        self.bhapus.setText(_translate("AdminWindow", "HAPUS"))
        self.breload.setText(_translate("AdminWindow", "RELOAD"))
        self.lidpel.setPlaceholderText(
            _translate("AdminWindow", "ID PELANGGAN"))

    def koneksi(self):
        try:
            mydb = mc.connect(host="localhost", user="root", password="",
                              db="db_paspelabuhan")
            self.lketerangan.setText("Berhasil Terkoneksi ke Database")
        except mc.Error as e:
            self.lketerangan.setText("Gagal Terkoneksi ke Database")

    def timing(self):
        time = datetime.now()
        self.showtime = time.strftime(
            "%H : %M : %S" + " WIB" + " / %d - %m - %Y")
        self.waktu.setText(self.showtime)

    def readpelanggan(self):
        mydb = mc.connect(host="localhost", user="root", password="",
                          db="db_paspelabuhan")
        cur = mydb.cursor()
        query = "SELECT * FROM pelanggan"
        cur.execute(query)
        data = cur.fetchall()
        self.tpelanggan.setRowCount(0)

        for row_number, row_data in enumerate(data):
            self.tpelanggan.insertRow(row_number)
            for column_number, data1 in enumerate(row_data):
                self.tpelanggan.setItem(
                    row_number, column_number, QtWidgets.QTableWidgetItem(str(data1)))
        self.lketerangan.setText("Data di Reload")

    def deletepelanggan(self):
        mydb = mc.connect(host="localhost", user="root", password="",
                          db="db_paspelabuhan")
        cur = mydb.cursor()
        idpel = self.lidpel.text()

        query = "DELETE FROM pelanggan WHERE idpel = %s"
        value = (idpel,)

        try:
            if (idpel == ""):
                self.lketerangan.setText("Id Pelanggan Tidak Boleh Kosong!!")
            else:
                cur.execute(query, value)
                mydb.commit()
                self.lketerangan.setText(
                    "Id Pelanggan = " + idpel + " Dihapus")
                self.lidpel.setText("")
        except:
            self.lketerangan.setText("Gagal Menghapus Data")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminWindow()
    ui.setupUi(AdminWindow)
    AdminWindow.show()
    sys.exit(app.exec_())
