# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTime, QTimer
from datetime import datetime

import logo
import mysql.connector as mc
import pandas as pd


class Ui_DataWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedHeight(800)
        MainWindow.setFixedWidth(1200)
        MainWindow.setGeometry(QtCore.QRect(85, 25, 1200, 800))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header1 = QtWidgets.QLabel(self.centralwidget)
        self.header1.setGeometry(QtCore.QRect(250, 10, 941, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.header1.setFont(font)
        self.header1.setAlignment(QtCore.Qt.AlignCenter)
        self.header1.setObjectName("header1")
        self.header2 = QtWidgets.QLabel(self.centralwidget)
        self.header2.setGeometry(QtCore.QRect(390, 70, 631, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.header2.setFont(font)
        self.header2.setAlignment(QtCore.Qt.AlignCenter)
        self.header2.setObjectName("header2")
        self.background1 = QtWidgets.QLabel(self.centralwidget)
        self.background1.setGeometry(QtCore.QRect(0, 170, 1200, 581))
        self.background1.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.background1.setText("")
        self.background1.setObjectName("background1")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 231, 151))
        self.logo.setStyleSheet("image: url(:/logo/logo.png);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.klogin = QtWidgets.QLabel(self.centralwidget)
        self.klogin.setGeometry(QtCore.QRect(10, 170, 291, 41))
        self.preload = QtWidgets.QPushButton(self.centralwidget)
        self.preload.setGeometry(QtCore.QRect(18, 202, 100, 25))
        self.preload.setText("RELOAD")
        self.preload.clicked.connect(self.readdata)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.klogin.setFont(font)
        self.klogin.setObjectName("klogin")
        self.waktu = QtWidgets.QLabel(self.centralwidget)
        self.waktu.setGeometry(QtCore.QRect(890, 170, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.waktu.setFont(font)
        self.waktu.setAlignment(QtCore.Qt.AlignCenter)
        self.waktu.setObjectName("waktu")
        self.keterangan = QtWidgets.QLabel(self.centralwidget)
        self.keterangan.setGeometry(QtCore.QRect(454, 170, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.keterangan.setFont(font)
        self.keterangan.setStyleSheet("background-color: rgb(99, 99, 99);\n"
                                      "color: white;\n"
                                      "")
        self.keterangan.setAlignment(QtCore.Qt.AlignCenter)
        self.keterangan.setObjectName("keterangan")
        self.tpelanggan = QtWidgets.QTableWidget(self.centralwidget)
        self.tpelanggan.setGeometry(QtCore.QRect(680, 230, 501, 501))
        self.tpelanggan.setObjectName("tpelanggan")
        self.tpelanggan.setColumnCount(0)
        self.tpelanggan.setRowCount(0)
        self.bgkiri = QtWidgets.QLabel(self.centralwidget)
        self.bgkiri.setGeometry(QtCore.QRect(20, 230, 641, 501))
        self.bgkiri.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.bgkiri.setText("")
        self.bgkiri.setObjectName("bgkiri")
        self.cbulanawal = QtWidgets.QComboBox(self.centralwidget)
        self.cbulanawal.setGeometry(QtCore.QRect(380, 240, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cbulanawal.setFont(font)
        self.cbulanawal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbulanawal.setAutoFillBackground(False)
        self.cbulanawal.setEditable(False)
        self.cbulanawal.setObjectName("cbulanawal")
        self.cbulanawal.addItem("")
        self.cbulanawal.addItem("")
        self.cbulanawal.addItem("")
        self.cbulanawal.addItem("")
        self.cbulanawal.addItem("")
        self.cbulanawal.addItem("")
        self.cbulanawal.addItem("")
        self.cbulanawal.addItem("")
        self.cbulanawal.addItem("")
        self.cbulanawal.addItem("")
        self.cbulanawal.addItem("")
        self.cbulanawal.addItem("")
        self.cbulanakhir = QtWidgets.QComboBox(self.centralwidget)
        self.cbulanakhir.setGeometry(QtCore.QRect(380, 300, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cbulanakhir.setFont(font)
        self.cbulanakhir.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbulanakhir.setAutoFillBackground(False)
        self.cbulanakhir.setEditable(False)
        self.cbulanakhir.setObjectName("cbulanakhir")
        self.cbulanakhir.addItem("")
        self.cbulanakhir.addItem("")
        self.cbulanakhir.addItem("")
        self.cbulanakhir.addItem("")
        self.cbulanakhir.addItem("")
        self.cbulanakhir.addItem("")
        self.cbulanakhir.addItem("")
        self.cbulanakhir.addItem("")
        self.cbulanakhir.addItem("")
        self.cbulanakhir.addItem("")
        self.cbulanakhir.addItem("")
        self.cbulanakhir.addItem("")
        self.ctahun = QtWidgets.QComboBox(self.centralwidget)
        self.ctahun.setGeometry(QtCore.QRect(380, 360, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ctahun.setFont(font)
        self.ctahun.setObjectName("ctahun")
        self.ctahun.addItem("")
        self.ctahun.addItem("")
        self.ctahun.addItem("")
        self.ctahun.addItem("")
        self.ctahun.addItem("")
        self.ctahun.addItem("")
        self.ctahun.addItem("")
        self.ctahun.addItem("")
        self.ctahun.addItem("")
        self.cjenis = QtWidgets.QComboBox(self.centralwidget)
        self.cjenis.setGeometry(QtCore.QRect(380, 420, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cjenis.setFont(font)
        self.cjenis.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cjenis.setAutoFillBackground(False)
        self.cjenis.setEditable(False)
        self.cjenis.setObjectName("cjenis")
        self.cjenis.addItem("")
        self.cjenis.addItem("")
        self.cjenis.addItem("")
        self.cjenis.addItem("")
        self.cjenis.addItem("")
        self.cjenis.addItem("")
        self.lketerangan = QtWidgets.QLineEdit(self.centralwidget)
        self.lketerangan.setGeometry(QtCore.QRect(40, 480, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lketerangan.setFont(font)
        self.lketerangan.setAlignment(QtCore.Qt.AlignCenter)
        self.lketerangan.setObjectName("lketerangan")
        self.lejumlah = QtWidgets.QLineEdit(self.centralwidget)
        self.lejumlah.setGeometry(QtCore.QRect(380, 530, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lejumlah.setFont(font)
        self.lejumlah.setText("")
        self.lejumlah.setReadOnly(False)
        self.lejumlah.setObjectName("lejumlah")
        self.letotal = QtWidgets.QLineEdit(self.centralwidget)
        self.letotal.setGeometry(QtCore.QRect(380, 590, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.letotal.setFont(font)
        self.letotal.setReadOnly(False)
        self.letotal.setObjectName("letotal")
        self.phasil = QtWidgets.QPushButton(self.centralwidget)
        self.phasil.setGeometry(QtCore.QRect(50, 660, 271, 51))
        self.phasil.clicked.connect(self.hasil)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.phasil.setFont(font)
        self.phasil.setObjectName("phasil")
        self.pconvert = QtWidgets.QPushButton(self.centralwidget)
        self.pconvert.setGeometry(QtCore.QRect(360, 660, 271, 51))
        self.pconvert.clicked.connect(self.exportToExcell)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pconvert.setFont(font)
        self.pconvert.setObjectName("pconvert")
        self.ljumlah = QtWidgets.QLabel(self.centralwidget)
        self.ljumlah.setGeometry(QtCore.QRect(50, 530, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.ljumlah.setFont(font)
        self.ljumlah.setObjectName("ljumlah")
        self.ltotal = QtWidgets.QLabel(self.centralwidget)
        self.ltotal.setGeometry(QtCore.QRect(50, 590, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.ltotal.setFont(font)
        self.ltotal.setObjectName("ltotal")
        self.lbulan = QtWidgets.QLabel(self.centralwidget)
        self.lbulan.setGeometry(QtCore.QRect(50, 240, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lbulan.setFont(font)
        self.lbulan.setObjectName("lbulan")
        self.lsbulan = QtWidgets.QLabel(self.centralwidget)
        self.lsbulan.setGeometry(QtCore.QRect(50, 300, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lsbulan.setFont(font)
        self.lsbulan.setObjectName("lsbulan")
        self.ltahun = QtWidgets.QLabel(self.centralwidget)
        self.ltahun.setGeometry(QtCore.QRect(50, 360, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.ltahun.setFont(font)
        self.ltahun.setObjectName("ltahun")
        self.ljenis = QtWidgets.QLabel(self.centralwidget)
        self.ljenis.setGeometry(QtCore.QRect(50, 420, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.ljenis.setFont(font)
        self.ljenis.setObjectName("ljenis")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.header = ["ID", "Status", "Jenis",
                       "Plat Nomor", "Jam", "Tanggal", "Biaya"]

        self.headershow = ["ID", "Jenis", "Tanggal", "Biaya"]

        self.tpelanggan.setColumnWidth(1, 115)

        self.timer = QTimer()
        self.timer.timeout.connect(self.timing)
        self.timer.start(1000)

        self.lwaktuhide = QtWidgets.QLineEdit(self.centralwidget)
        self.lwaktuhide.setGeometry(QtCore.QRect(0, 0, 0, 0))

        self.timing()
        self.koneksi()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LAPORAN DATA"))
        self.header1.setText(_translate(
            "MainWindow", "OPERATOR PAS MASUK PELABUHAN"))
        self.header2.setText(_translate("MainWindow", "UPP KELAS III SAPUDI"))
        self.klogin.setText(_translate("MainWindow", "SUPER ADMIN"))

        self.keterangan.setText(_translate("MainWindow", "LAPORAN DATA"))
        self.cbulanawal.setCurrentText(_translate("MainWindow", "JANUARI"))
        self.cbulanawal.setItemText(0, _translate("MainWindow", "JANUARI"))
        self.cbulanawal.setItemText(1, _translate("MainWindow", "FEBRUARI"))
        self.cbulanawal.setItemText(2, _translate("MainWindow", "MARET"))
        self.cbulanawal.setItemText(3, _translate("MainWindow", "APRIL"))
        self.cbulanawal.setItemText(4, _translate("MainWindow", "MEI"))
        self.cbulanawal.setItemText(5, _translate("MainWindow", "JUNI"))
        self.cbulanawal.setItemText(6, _translate("MainWindow", "JULI"))
        self.cbulanawal.setItemText(7, _translate("MainWindow", "AGUSTUS"))
        self.cbulanawal.setItemText(8, _translate("MainWindow", "SEPTEMBER"))
        self.cbulanawal.setItemText(9, _translate("MainWindow", "OKTOBER"))
        self.cbulanawal.setItemText(10, _translate("MainWindow", "NOVEMBER"))
        self.cbulanawal.setItemText(11, _translate("MainWindow", "DESEMBER"))
        self.cbulanakhir.setCurrentText(_translate("MainWindow", "JANUARI"))
        self.cbulanakhir.setItemText(0, _translate("MainWindow", "JANUARI"))
        self.cbulanakhir.setItemText(1, _translate("MainWindow", "FEBRUARI"))
        self.cbulanakhir.setItemText(2, _translate("MainWindow", "MARET"))
        self.cbulanakhir.setItemText(3, _translate("MainWindow", "APRIL"))
        self.cbulanakhir.setItemText(4, _translate("MainWindow", "MEI"))
        self.cbulanakhir.setItemText(5, _translate("MainWindow", "JUNI"))
        self.cbulanakhir.setItemText(6, _translate("MainWindow", "JULI"))
        self.cbulanakhir.setItemText(7, _translate("MainWindow", "AGUSTUS"))
        self.cbulanakhir.setItemText(8, _translate("MainWindow", "SEPTEMBER"))
        self.cbulanakhir.setItemText(9, _translate("MainWindow", "OKTOBER"))
        self.cbulanakhir.setItemText(10, _translate("MainWindow", "NOVEMBER"))
        self.cbulanakhir.setItemText(11, _translate("MainWindow", "DESEMBER"))
        self.ctahun.setItemText(0, _translate("MainWindow", "2022"))
        self.ctahun.setItemText(1, _translate("MainWindow", "2023"))
        self.ctahun.setItemText(2, _translate("MainWindow", "2024"))
        self.ctahun.setItemText(3, _translate("MainWindow", "2025"))
        self.ctahun.setItemText(4, _translate("MainWindow", "2026"))
        self.ctahun.setItemText(5, _translate("MainWindow", "2027"))
        self.ctahun.setItemText(6, _translate("MainWindow", "2028"))
        self.ctahun.setItemText(7, _translate("MainWindow", "2029"))
        self.ctahun.setItemText(8, _translate("MainWindow", "2030"))
        self.cjenis.setCurrentText(_translate("MainWindow", "SEMUA"))
        self.cjenis.setItemText(0, _translate("MainWindow", "SEMUA"))
        self.cjenis.setItemText(1, _translate("MainWindow", "ORANG"))
        self.cjenis.setItemText(2, _translate("MainWindow", "RODA 2"))
        self.cjenis.setItemText(3, _translate("MainWindow", "RODA 3"))
        self.cjenis.setItemText(4, _translate("MainWindow", "RODA 4"))
        self.cjenis.setItemText(5, _translate("MainWindow", "TRUCK"))
        self.phasil.setText(_translate("MainWindow", "HASIL"))
        self.pconvert.setText(_translate("MainWindow", "CONVERT"))
        self.ljumlah.setText(_translate("MainWindow", "JUMLAH"))
        self.ltotal.setText(_translate("MainWindow", "TOTAL PENDAPATAN"))
        self.lbulan.setText(_translate("MainWindow", "BULAN"))
        self.lsbulan.setText(_translate("MainWindow", "SAMPAI BULAN"))
        self.ltahun.setText(_translate("MainWindow", "TAHUN"))
        self.ljenis.setText(_translate("MainWindow", "JENIS"))

    def timing(self):
        time = datetime.now()
        self.showtime = time.strftime(
            "%H : %M : %S" + " WIB" + " / %d - %m - %Y")
        self.hidetime = time.strftime("%H-%M-%S"+" WIB " + "%d-%m-%Y")
        self.waktu.setText(self.showtime)
        self.lwaktuhide.setText(self.hidetime)

    def koneksi(self):
        try:
            mydb = mc.connect(host="localhost", user="root", password="",
                              db="db_paspelabuhan")
            self.lketerangan.setText("Berhasil Terkoneksi ke Database")
        except mc.Error as e:
            self.lketerangan.setText("Gagal Terkoneksi ke Database")

    def hasil(self):
        bulan = str(self.cbulanawal.currentText())
        sbulan = str(self.cbulanakhir.currentText())
        tahun = str(self.ctahun.currentText())
        jenis = str(self.cjenis.currentText())

        self.lketerangan.setText(
            "Data Dari " + bulan + " - " + sbulan + " Tahun " + tahun + " Jenis " + jenis)
        self.jumlah()

    def readdata(self, datas=""):
        mydb = mc.connect(host="localhost", user="root", password="",
                          db="db_paspelabuhan")
        cur = mydb.cursor()
        query = "SELECT * FROM pelanggan"
        cur.execute(query)
        data = cur.fetchall()

        self.tpelanggan.setColumnCount(len(self.header))
        for i in range(len(self.header)):
            self.tpelanggan.setHorizontalHeaderItem(
                i, QtWidgets.QTableWidgetItem(self.header[i]))

        self.tpelanggan.setRowCount(0)

        for row_number, row_data in enumerate(data):
            self.tpelanggan.insertRow(row_number)
            for column_number, data1 in enumerate(row_data):
                self.tpelanggan.setItem(
                    row_number, column_number, QtWidgets.QTableWidgetItem(str(data1)))
        self.lejumlah.setText("-")
        self.letotal.setText("-")

    def showData(self, data):

        self.tpelanggan.setColumnCount(len(self.headershow))
        for i in range(len(self.headershow)):
            self.tpelanggan.setHorizontalHeaderItem(
                i, QtWidgets.QTableWidgetItem(self.headershow[i]))

        self.tpelanggan.setRowCount(0)

        for row_number, row_data in enumerate(data):
            self.tpelanggan.insertRow(row_number)
            for column_number, data1 in enumerate(row_data):
                self.tpelanggan.setItem(
                    row_number, column_number, QtWidgets.QTableWidgetItem(str(data1)))

    def jumlah(self):
        dict_bulan = {
            "JANUARI": 1,
            "FEBRUARI": 2,
            "MARET": 3,
            "APRIL": 4,
            "MEI": 5,
            "JUNI": 6,
            "JULI": 7,
            "AGUSTUS": 8,
            "SEPTEMBER": 9,
            "OKTOBER": 10,
            "NOVEMBER": 11,
            "DESEMBER": 12, }
        bulan = str(self.cbulanawal.currentText())
        sbulan = str(self.cbulanakhir.currentText())
        tahun = str(self.ctahun.currentText())
        jenis = str(self.cjenis.currentText())

        mydb = mc.connect(host="localhost", user="root", password="",
                          db="db_paspelabuhan")
        cur = mydb.cursor()
        if jenis != "SEMUA":
            query = "SELECT idpel, jenis, tanggal, biaya FROM pelanggan WHERE jenis = %s AND tanggal BETWEEN '%s-%s-1' AND '%s-%s-1'"
            value = (jenis, int(tahun), dict_bulan[bulan], int(
                tahun), dict_bulan[sbulan])
        else:
            query = "SELECT idpel, jenis, tanggal, biaya FROM pelanggan WHERE tanggal BETWEEN '%s-%s-1' AND '%s-%s-1'"
            value = (int(tahun), dict_bulan[bulan], int(
                tahun), dict_bulan[sbulan])
        cur.execute(query, value)
        result = cur.fetchall()
        self.lejumlah.setText(str(len(result)))
        total = 0
        for i in result:
            total += i[-1]
        self.letotal.setText(str(total))
        self.showData(result)

    def exportToExcell(self):
        columnHeader = ["jumlah", "Total Pendapatan", ]
        for j in range(self.tpelanggan.model().columnCount()):
            columnHeader.append(
                self.tpelanggan.horizontalHeaderItem(j).text())

        df = pd.DataFrame(columns=columnHeader)

        for row in range(self.tpelanggan.rowCount()):
            for col in range(self.tpelanggan.columnCount()):
                df.at[row, columnHeader[col+2]] = self.tpelanggan.item(
                    row, col).text()
        df.at[row, columnHeader[0]] = self.lejumlah.text()
        df.at[row, columnHeader[1]] = self.letotal.text()
        waktu = self.lwaktuhide.text()
        namadata = "data export " + waktu + ".xlsx"
        df.to_excel(str(namadata), index=False)
        self.lketerangan.setText("Data Berhasil di Convert")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_DataWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
