# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from black import err
from MAIN import Ui_MainWindow
from SUPERADMIN import Ui_SAdminWindow

import mysql.connector as mc


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setFixedHeight(800)
        Login.setFixedWidth(1200)
        Login.setGeometry(QtCore.QRect(85, 5, 1200, 800))
        Login.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Login.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.bglabel = QtWidgets.QLabel(Login)
        self.bglabel.setGeometry(QtCore.QRect(290, 260, 621, 331))
        self.bglabel.setStyleSheet("background-color: rgb(189, 189, 189);\n"
                                   "border-radius: 40px;")
        self.bglabel.setText("")
        self.bglabel.setObjectName("bglabel")
        self.llogin = QtWidgets.QLabel(Login)
        self.llogin.setGeometry(QtCore.QRect(410, 290, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.llogin.setFont(font)
        self.llogin.setAlignment(QtCore.Qt.AlignCenter)
        self.llogin.setObjectName("llogin")
        self.lusername = QtWidgets.QLineEdit(Login)
        self.lusername.setGeometry(QtCore.QRect(380, 360, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.lusername.setFont(font)
        self.lusername.setStyleSheet("border-radius: 20px;")
        self.lusername.setText("")
        self.lusername.setAlignment(QtCore.Qt.AlignCenter)
        self.lusername.setObjectName("lusername")
        self.lpassword = QtWidgets.QLineEdit(Login)
        self.lpassword.setGeometry(QtCore.QRect(380, 430, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.lpassword.setFont(font)
        self.lpassword.setStyleSheet("border-radius: 20px;")
        self.lpassword.setText("")
        self.lpassword.setAlignment(QtCore.Qt.AlignCenter)
        self.lpassword.setObjectName("lpassword")
        self.pblogin = QtWidgets.QPushButton(Login)
        self.pblogin.setGeometry(QtCore.QRect(370, 500, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.pblogin.setFont(font)
        self.pblogin.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pblogin.setObjectName("pblogin")
        self.pblogin.clicked.connect(self.login)
        self.pbreset = QtWidgets.QPushButton(Login)
        self.pbreset.setGeometry(QtCore.QRect(630, 500, 201, 51))
        self.pbreset.clicked.connect(self.reset)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.pbreset.setFont(font)
        self.pbreset.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pbreset.setObjectName("pbreset")
        self.lketerangan = QtWidgets.QLabel(Login)
        self.lketerangan.setGeometry(QtCore.QRect(370, 560, 471, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font
        self.lketerangan.setFont(font)
        self.lketerangan.setStyleSheet("color: rgb(255, 0, 0);")
        self.lketerangan.setObjectName("lketerangan")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.llogin.setText(_translate("Login", "LOGIN OPERATOR"))
        self.lusername.setPlaceholderText(_translate("Login", "USERNAME"))
        self.lpassword.setPlaceholderText(_translate("Login", "PASSWORD"))
        self.pblogin.setText(_translate("Login", "LOGIN"))
        self.pbreset.setText(_translate("Login", "RESET"))
        self.lketerangan.setText(_translate(
            "Login", "/"))

    def login(self):
        try:
            username = self.lusername.text()
            passw = self.lpassword.text()

            mydb = mc.connect(host="localhost", user="root",
                              password="", db="db_paspelabuhan")
            cur = mydb.cursor()
            query = "SELECT nama, username, password from admin WHERE username = %s AND password = %s "
            values = (username, passw)
            cur.execute(query, values)

            result = cur.fetchone()
            if result == None:
                self.lketerangan.setText(
                    "ANDA GAGAL LOGIN, DATA YANG ANDA MASUKKAN SALAH")
            elif result[0] == "Super Admin":
                self.openAdmin()
                Login.close()
            else:
                self.openMain()
                Login.close()

        except mc.Error as e:
            self.lketerangan.setText(
                "ANDA GAGAL LOGIN, TIDAK TERKONEKSI KE DATABASE")

    def openMain(self):
        self.windowMain = QtWidgets.QMainWindow()
        self.showWindowMain = Ui_MainWindow()
        self.showWindowMain.setupUi(self.windowMain)
        self.windowMain.show()

    def openAdmin(self):
        self.windowAdmin = QtWidgets.QMainWindow()
        self.showWindowAdmin = Ui_SAdminWindow()
        self.showWindowAdmin.setupUi(self.windowAdmin)
        self.windowAdmin.show()

    def reset(self):
        self.lusername.setText("")
        self.lpassword.setText("")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
