# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTime, QTimer
from datetime import datetime
from ADMIN import Ui_AdminWindow
import logo
import mysql.connector as mc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedHeight(800)
        MainWindow.setFixedWidth(1200)
        MainWindow.setGeometry(QtCore.QRect(85, 25, 1200, 800))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header1 = QtWidgets.QLabel(self.centralwidget)
        self.header1.setGeometry(QtCore.QRect(250, 10, 941, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.header1.setFont(font)
        self.header1.setAlignment(QtCore.Qt.AlignCenter)
        self.header1.setObjectName("header1")
        self.header2 = QtWidgets.QLabel(self.centralwidget)
        self.header2.setGeometry(QtCore.QRect(390, 70, 631, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.header2.setFont(font)
        self.header2.setAlignment(QtCore.Qt.AlignCenter)
        self.header2.setObjectName("header2")
        self.background1 = QtWidgets.QLabel(self.centralwidget)
        self.background1.setGeometry(QtCore.QRect(0, 170, 1200, 581))
        self.background1.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.background1.setText("")
        self.background1.setObjectName("background1")
        self.date = QtWidgets.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(943, 200, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.date.setFont(font)
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(1000, 170, 165, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.time.setFont(font)
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 231, 151))
        self.logo.setStyleSheet("image: url(:/logo/logo.png);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.jenis = QtWidgets.QComboBox(self.centralwidget)
        self.jenis.setGeometry(QtCore.QRect(460, 240, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.jenis.setFont(font)
        self.jenis.setObjectName("jenis")
        self.jenis.addItem("")
        self.jenis.addItem("")
        self.jenis.addItem("")
        self.ljenis = QtWidgets.QLabel(self.centralwidget)
        self.ljenis.setGeometry(QtCore.QRect(460, 200, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ljenis.setFont(font)
        self.ljenis.setObjectName("ljenis")
        self.ljenis_kendaraan = QtWidgets.QLabel(self.centralwidget)
        self.ljenis_kendaraan.setGeometry(QtCore.QRect(700, 200, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ljenis_kendaraan.setFont(font)
        self.ljenis_kendaraan.setObjectName("ljenis_kendaraan")
        self.jenis_kendaraan = QtWidgets.QComboBox(self.centralwidget)
        self.jenis_kendaraan.setGeometry(QtCore.QRect(700, 240, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.jenis_kendaraan.setFont(font)
        self.jenis_kendaraan.setObjectName("jenis_kendaraan")
        self.jenis_kendaraan.addItem("")
        self.jenis_kendaraan.addItem("")
        self.jenis_kendaraan.addItem("")
        self.jenis_kendaraan.addItem("")
        self.jenis_kendaraan.addItem("")
        self.platnomor = QtWidgets.QLineEdit(self.centralwidget)
        self.platnomor.setGeometry(QtCore.QRect(460, 310, 731, 91))
        self.platnomor.setPlaceholderText("PLAT NOMOR")
        self.platnomor.setStyleSheet("text-transform: uppercase;")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.platnomor.setFont(font)
        self.platnomor.setAlignment(QtCore.Qt.AlignCenter)
        self.platnomor.setObjectName("platnomor")
        self.bcek = QtWidgets.QPushButton(self.centralwidget)
        self.bcek.setGeometry(QtCore.QRect(460, 410, 300, 61))
        self.bcek.clicked.connect(self.cek)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.bcek.setFont(font)
        self.bcek.setObjectName("bcek")
        self.bgketerangan = QtWidgets.QLabel(self.centralwidget)
        self.bgketerangan.setGeometry(QtCore.QRect(10, 480, 531, 261))
        self.bgketerangan.setStyleSheet(
            "background-color: rgb(225, 225, 225);")
        self.bgketerangan.setText("")
        self.bgketerangan.setObjectName("bgketerangan")
        self.bgbiaya = QtWidgets.QLabel(self.centralwidget)
        self.bgbiaya.setGeometry(QtCore.QRect(550, 480, 641, 261))
        self.bgbiaya.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.bgbiaya.setText("")
        self.bgbiaya.setObjectName("bgbiaya")
        self.lketerangan = QtWidgets.QLabel(self.centralwidget)
        self.lketerangan.setGeometry(QtCore.QRect(230, 500, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lketerangan.setFont(font)
        self.lketerangan.setObjectName("lketerangan")
        self.kstatus = QtWidgets.QLabel(self.centralwidget)
        self.kstatus.setGeometry(QtCore.QRect(20, 530, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.kstatus.setFont(font)
        self.kstatus.setObjectName("kstatus")
        self.kjenis = QtWidgets.QLabel(self.centralwidget)
        self.kjenis.setGeometry(QtCore.QRect(20, 570, 121, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.kjenis.setFont(font)
        self.kjenis.setObjectName("kjenis")
        self.lplatnomor = QtWidgets.QLabel(self.centralwidget)
        self.lplatnomor.setGeometry(QtCore.QRect(20, 610, 121, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lplatnomor.setFont(font)
        self.lplatnomor.setObjectName("lplatnomor")
        self.kbiaya = QtWidgets.QLabel(self.centralwidget)
        self.kbiaya.setGeometry(QtCore.QRect(680, 500, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.kbiaya.setFont(font)
        self.kbiaya.setObjectName("kbiaya")
        self.biaya = QtWidgets.QLineEdit(self.centralwidget)
        self.biaya.setGeometry(QtCore.QRect(580, 570, 581, 141))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.biaya.setFont(font)
        self.biaya.setAlignment(QtCore.Qt.AlignCenter)
        self.biaya.setReadOnly(True)
        self.biaya.setObjectName("biaya")
        self.ktanggal = QtWidgets.QLabel(self.centralwidget)
        self.ktanggal.setGeometry(QtCore.QRect(20, 690, 121, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ktanggal.setFont(font)
        self.ktanggal.setObjectName("ktanggal")
        self.kjam = QtWidgets.QLabel(self.centralwidget)
        self.kjam.setGeometry(QtCore.QRect(20, 650, 121, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.kjam.setFont(font)
        self.kjam.setObjectName("kjam")
        self.lkstatus = QtWidgets.QLineEdit(self.centralwidget)
        self.lkstatus.setGeometry(QtCore.QRect(190, 530, 331, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lkstatus.setFont(font)
        self.lkstatus.setReadOnly(True)
        self.lkstatus.setObjectName("lkstatus")
        self.lktanggal = QtWidgets.QLineEdit(self.centralwidget)
        self.lktanggal.setGeometry(QtCore.QRect(190, 690, 331, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lktanggal.setFont(font)
        self.lktanggal.setReadOnly(True)
        self.lktanggal.setObjectName("lktanggal")
        self.lkjam = QtWidgets.QLineEdit(self.centralwidget)
        self.lkjam.setGeometry(QtCore.QRect(190, 650, 331, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lkjam.setFont(font)
        self.lkjam.setReadOnly(True)
        self.lkjam.setObjectName("lkjam")
        self.lkplatnomor = QtWidgets.QLineEdit(self.centralwidget)
        self.lkplatnomor.setGeometry(QtCore.QRect(190, 610, 331, 25))
        self.lkplatnomor.setStyleSheet("text-transform: uppercase;")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lkplatnomor.setFont(font)
        self.lkplatnomor.setReadOnly(True)
        self.lkplatnomor.setObjectName("lkplatnomor")
        self.lkjenis = QtWidgets.QLineEdit(self.centralwidget)
        self.lkjenis.setGeometry(QtCore.QRect(190, 570, 331, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lkjenis.setFont(font)
        self.lkjenis.setReadOnly(True)
        self.lkjenis.setObjectName("lkjenis")
        self.bsimpan = QtWidgets.QPushButton(self.centralwidget)
        self.bsimpan.setGeometry(QtCore.QRect(765, 410, 428, 61))
        self.bsimpan.clicked.connect(self.tambahdata)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.bsimpan.setFont(font)
        self.bsimpan.setObjectName("bsimpan")
        self.tableview = QtWidgets.QTableWidget(self.centralwidget)
        self.tableview.setGeometry(QtCore.QRect(10, 180, 441, 291))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.tableview.setFont(font)
        self.tableview.setObjectName("tableview")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.info = QtWidgets.QLabel(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(940, 270, 280, 25))
        self.info.setText("")
        font = QtGui.QFont("Arial", 12)
        self.info.setStyleSheet("color : red")
        self.info.setFont(font)

        self.bmanage = QtWidgets.QPushButton(self.centralwidget)
        self.bmanage.setGeometry(QtCore.QRect(1090, 180, 101, 41))
        self.bmanage.setText("MANAGE")
        self.bmanage.clicked.connect(self.openAdmin)

        self.timer = QTimer()
        self.timer.timeout.connect(self.waktu)

        self.tableview.setColumnCount(7)
        self.tableview.setHorizontalHeaderItem(
            0, QtWidgets.QTableWidgetItem("ID"))
        self.tableview.setColumnWidth(0, 50)
        self.tableview.setHorizontalHeaderItem(
            1, QtWidgets.QTableWidgetItem("Status"))
        self.tableview.setHorizontalHeaderItem(
            2, QtWidgets.QTableWidgetItem("Jenis"))
        self.tableview.setHorizontalHeaderItem(
            3, QtWidgets.QTableWidgetItem("Plat Nomor"))
        self.tableview.setHorizontalHeaderItem(
            4, QtWidgets.QTableWidgetItem("Jam"))
        self.tableview.setHorizontalHeaderItem(
            5, QtWidgets.QTableWidgetItem("Tanggal"))
        self.tableview.setHorizontalHeaderItem(
            6, QtWidgets.QTableWidgetItem("Biaya"))

        self.time.setHidden(True)
        self.date.setHidden(True)

        # memulai waktu dan melooping perdetik
        self.timer.start(1000)

        self.waktu()
        self.koneksi()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "OPERATOR PAS MASUK PELABUHAN UPP KELAS III SAPUDI"))
        self.header1.setText(_translate(
            "MainWindow", "OPERATOR PAS MASUK PELABUHAN"))
        self.header2.setText(_translate("MainWindow", "UPP KELAS III SAPUDI"))
        self.jenis.setItemText(0, _translate("MainWindow", "UMUM"))
        self.jenis.setItemText(1, _translate("MainWindow", "KARYAWAN"))
        self.jenis.setItemText(2, _translate("MainWindow", "ABK"))
        self.ljenis.setText(_translate("MainWindow", "STATUS :"))
        self.ljenis_kendaraan.setText(_translate("MainWindow", "JENIS :"))
        self.jenis_kendaraan.setItemText(0, _translate("MainWindow", "ORANG"))
        self.jenis_kendaraan.setItemText(1, _translate("MainWindow", "RODA 2"))
        self.jenis_kendaraan.setItemText(2, _translate("MainWindow", "RODA 3"))
        self.jenis_kendaraan.setItemText(3, _translate("MainWindow", "RODA 4"))
        self.jenis_kendaraan.setItemText(4, _translate("MainWindow", "TRUCK"))
        self.bcek.setText(_translate("MainWindow", "CEK"))
        self.lketerangan.setText(_translate("MainWindow", "KETERANGAN :"))
        self.kstatus.setText(_translate("MainWindow", "STATUS"))
        self.kjenis.setText(_translate("MainWindow", "JENIS"))
        self.lplatnomor.setText(_translate("MainWindow", "PLAT NOMOR"))
        self.kbiaya.setText(_translate(
            "MainWindow", "BIAYA YANG PERLU DI BAYAR"))
        self.ktanggal.setText(_translate("MainWindow", "TANGGAL"))
        self.kjam.setText(_translate("MainWindow", "JAM"))
        self.bsimpan.setText(_translate("MainWindow", "SIMPAN"))

    def waktu(self):
        time = datetime.now()
        self.showtime = time.strftime("%H : %M : %S")
        self.showdate = time.strftime("%d - %m - %Y")
        self.timedatabase = time.strftime("%H:%M:%S")
        self.datedatabase = time.strftime("%Y-%m-%d")
        self.time.setText(self.showtime + "  WIB")
        self.date.setText(self.showdate)

    def koneksi(self):
        try:
            mydb = mc.connect(host="localhost", user="root", password="",
                              db="db_paspelabuhan")
            self.info.setText("Berhasil Terkoneksi ke Database")
        except mc.Error as e:
            self.info.setText("Gagal Terkoneksi ke Database")

    def cek(self):
        status = str(self.jenis.currentText())
        jenis = str(self.jenis_kendaraan.currentText())
        platnomor = self.platnomor.text()

        if (status == "UMUM" and jenis == "ORANG"):
            self.biaya.setText("Rp. 2000")
            self.lkplatnomor.setText("-")
        if (status == "UMUM" and jenis == "RODA 2"):
            self.biaya.setText("Rp. 3000")
            self.platnomor.setReadOnly(False)
            self.lkplatnomor.setText(platnomor)
        if (status == "UMUM" and jenis == "RODA 3"):
            self.biaya.setText("Rp. 3000")
            self.lkplatnomor.setText(platnomor)
        if (status == "UMUM" and jenis == "RODA 4"):
            self.biaya.setText("Rp. 4000")
            self.lkplatnomor.setText(platnomor)
        if (status == "UMUM" and jenis == "TRUCK"):
            self.biaya.setText("Rp. 4000")
            self.lkplatnomor.setText(platnomor)
        if (status == "KARYAWAN" or status == "ABK"):
            self.biaya.setText("Rp. 0")
            self.lkplatnomor.setText(platnomor)
        if (status == "KARYAWAN" and jenis == "ORANG"):
            self.biaya.setText("Rp. 0")
            self.lkplatnomor.setText("-")
        if (status == "ABK" and jenis == "ORANG"):
            self.biaya.setText("Rp. 0")
            self.lkplatnomor.setText("-")

        # memberi nilai keterangan
        self.lkstatus.setText(status)
        self.lkjenis.setText(jenis)
        self.lkjam.setText(self.showtime + "  WIB")
        self.lktanggal.setText(self.showdate)

        # mengkosongkan kembali isian plat nomor
        self.platnomor.setText("")

        # info
        self.info.setText("Data Berhasil di Cek")

    def tambahdata(self):
        try:
            mydb = mc.connect(host="localhost", user="root", password="",
                              db="db_paspelabuhan")
            cur = mydb.cursor()
            status = str(self.jenis.currentText())
            jenis = str(self.jenis_kendaraan.currentText())
            platnomor = self.lkplatnomor.text()
            jam = self.timedatabase
            tanggal = self.datedatabase
            ketharga = self.biaya.text()

            if (ketharga == "Rp. 0"):
                harga = 0
            if (ketharga == "Rp. 2000"):
                harga = 2000
            if (ketharga == "Rp. 3000"):
                harga = 3000
            if (ketharga == "Rp. 4000"):
                harga = 4000

            query = "INSERT INTO pelanggan (status, jenis, plat_nomor, jam, tanggal, biaya) VALUES (%s, %s, %s, %s, %s, %s)"
            value = (status, jenis, platnomor, jam, tanggal, harga)

            cur.execute(query, value)
            mydb.commit()
            self.info.setText("Data Berhasil di Tambahkan")

            # mengkosongkan keterangan
            self.lkstatus.setText("")
            self.lkjenis.setText("")
            self.lkplatnomor.setText("")
            self.lkjam.setText("")
            self.lktanggal.setText("")
            self.biaya.setText("")

            self.upperData()
            self.readdata()

        except mc.Error as e:
            self.info.setText("Data Gagal di Tambahkan")

    def readdata(self):
        mydb = mc.connect(host="localhost", user="root", password="",
                          db="db_paspelabuhan")
        cur = mydb.cursor()
        query = "SELECT * FROM pelanggan"
        cur.execute(query)
        data = cur.fetchall()
        self.tableview.setRowCount(0)

        for row_number, row_data in enumerate(data):
            self.tableview.insertRow(row_number)
            for column_number, data1 in enumerate(row_data):
                self.tableview.setItem(
                    row_number, column_number, QtWidgets.QTableWidgetItem(str(data1)))

    def upperData(self):
        mydb = mc.connect(host="localhost", user="root", password="",
                          db="db_paspelabuhan")
        cur = mydb.cursor()
        query = "UPDATE pelanggan SET plat_nomor = UPPER(plat_nomor)"
        cur.execute(query)
        mydb.commit()

    def openAdmin(self):
        self.windowAdmin = QtWidgets.QMainWindow()
        self.showWindowAdmin = Ui_AdminWindow()
        self.showWindowAdmin.setupUi(self.windowAdmin)
        self.windowAdmin.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
