# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTime, QTimer
from datetime import datetime
from DATA import Ui_DataWindow
import logo
import mysql.connector as mc


class Ui_SAdminWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedHeight(800)
        MainWindow.setFixedWidth(1200)
        MainWindow.setGeometry(QtCore.QRect(85, 25, 1200, 800))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header1 = QtWidgets.QLabel(self.centralwidget)
        self.header1.setGeometry(QtCore.QRect(250, 10, 941, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.header1.setFont(font)
        self.header1.setAlignment(QtCore.Qt.AlignCenter)
        self.header1.setObjectName("header1")
        self.header2 = QtWidgets.QLabel(self.centralwidget)
        self.header2.setGeometry(QtCore.QRect(390, 70, 631, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.header2.setFont(font)
        self.header2.setAlignment(QtCore.Qt.AlignCenter)
        self.header2.setObjectName("header2")
        self.background1 = QtWidgets.QLabel(self.centralwidget)
        self.background1.setGeometry(QtCore.QRect(0, 170, 1200, 581))
        self.background1.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.background1.setText("")
        self.background1.setObjectName("background1")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 231, 151))
        self.logo.setStyleSheet("image: url(:/logo/logo.png);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.klogin = QtWidgets.QLabel(self.centralwidget)
        self.klogin.setGeometry(QtCore.QRect(10, 170, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.klogin.setFont(font)
        self.klogin.setObjectName("klogin")
        self.waktu = QtWidgets.QLabel(self.centralwidget)
        self.waktu.setGeometry(QtCore.QRect(890, 170, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.waktu.setFont(font)
        self.waktu.setAlignment(QtCore.Qt.AlignCenter)
        self.waktu.setObjectName("waktu")
        self.keterangan = QtWidgets.QLabel(self.centralwidget)
        self.keterangan.setGeometry(QtCore.QRect(454, 170, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.keterangan.setFont(font)
        self.keterangan.setStyleSheet("background-color: rgb(99, 99, 99);\n"
                                      "color: white;\n"
                                      "")
        self.keterangan.setAlignment(QtCore.Qt.AlignCenter)
        self.keterangan.setObjectName("keterangan")
        self.tpelanggan = QtWidgets.QTableWidget(self.centralwidget)
        self.tpelanggan.setGeometry(QtCore.QRect(10, 260, 741, 421))
        self.tpelanggan.setObjectName("tpelanggan")
        self.tpelanggan.setColumnCount(0)
        self.tpelanggan.setRowCount(0)
        self.tadministrator = QtWidgets.QTableWidget(
            self.centralwidget)
        self.tadministrator.setGeometry(QtCore.QRect(770, 220, 421, 341))
        self.tadministrator.setObjectName("tadministrator")
        self.tadministrator.setColumnCount(0)
        self.tadministrator.setRowCount(0)
        self.bhapus = QtWidgets.QPushButton(self.centralwidget)
        self.bhapus.setGeometry(QtCore.QRect(290, 690, 191, 41))
        self.bhapus.clicked.connect(self.deletepelanggan)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bhapus.setFont(font)
        self.bhapus.setObjectName("bhapus")
        self.breload = QtWidgets.QPushButton(self.centralwidget)
        self.breload.setGeometry(QtCore.QRect(10, 210, 191, 41))
        self.breload.clicked.connect(self.readpelanggan)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.breload.setFont(font)
        self.breload.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.breload.setObjectName("breload")
        self.lnama = QtWidgets.QLineEdit(self.centralwidget)
        self.lnama.setGeometry(QtCore.QRect(770, 570, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lnama.setFont(font)
        self.lnama.setAlignment(QtCore.Qt.AlignCenter)
        self.lnama.setObjectName("lnama")
        self.lnotelp = QtWidgets.QLineEdit(self.centralwidget)
        self.lnotelp.setGeometry(QtCore.QRect(770, 610, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lnotelp.setFont(font)
        self.lnotelp.setText("")
        self.lnotelp.setAlignment(QtCore.Qt.AlignCenter)
        self.lnotelp.setObjectName("lnotelp")
        self.lusername = QtWidgets.QLineEdit(self.centralwidget)
        self.lusername.setGeometry(QtCore.QRect(770, 650, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lusername.setFont(font)
        self.lusername.setText("")
        self.lusername.setAlignment(QtCore.Qt.AlignCenter)
        self.lusername.setObjectName("lusername")
        self.lpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lpassword.setGeometry(QtCore.QRect(990, 650, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lpassword.setFont(font)
        self.lpassword.setAlignment(QtCore.Qt.AlignCenter)
        self.lpassword.setObjectName("lpassword")
        self.btambahadmin = QtWidgets.QPushButton(self.centralwidget)
        self.btambahadmin.setGeometry(QtCore.QRect(770, 690, 211, 41))
        self.btambahadmin.clicked.connect(self.tambahadmin)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btambahadmin.setFont(font)
        self.btambahadmin.setObjectName("btambahadmin")
        self.bhapusadmin = QtWidgets.QPushButton(self.centralwidget)
        self.bhapusadmin.setGeometry(QtCore.QRect(990, 690, 201, 41))
        self.bhapusadmin.clicked.connect(self.deleteadmin)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bhapusadmin.setFont(font)
        self.bhapusadmin.setObjectName("bhapusadmin")
        self.lidpel = QtWidgets.QLineEdit(self.centralwidget)
        self.lidpel.setGeometry(QtCore.QRect(10, 690, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lidpel.setFont(font)
        self.lidpel.setText("")
        self.lidpel.setAlignment(QtCore.Qt.AlignCenter)
        self.lidpel.setObjectName("lidpel")
        self.bdata = QtWidgets.QPushButton(self.centralwidget)
        self.bdata.setGeometry(QtCore.QRect(220, 210, 191, 41))
        self.bdata.clicked.connect(self.openData)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.bdata.setFont(font)
        self.bdata.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.bdata.setObjectName("bdata")
        self.lketerangan = QtWidgets.QLabel(self.centralwidget)
        self.lketerangan.setGeometry(QtCore.QRect(520, 230, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lketerangan.setFont(font)
        self.lketerangan.setStyleSheet("background-color: rgb(206, 206, 206);\n"
                                       "color: rgb(255, 0, 0);")
        self.lketerangan.setObjectName("lketerangan")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.tpelanggan.setColumnCount(7)
        self.tpelanggan.setHorizontalHeaderItem(
            0, QtWidgets.QTableWidgetItem("ID"))
        self.tpelanggan.setHorizontalHeaderItem(
            1, QtWidgets.QTableWidgetItem("Status"))
        self.tpelanggan.setColumnWidth(1, 115)
        self.tpelanggan.setHorizontalHeaderItem(
            2, QtWidgets.QTableWidgetItem("Jenis"))
        self.tpelanggan.setHorizontalHeaderItem(
            3, QtWidgets.QTableWidgetItem("Plat Nomor"))
        self.tpelanggan.setHorizontalHeaderItem(
            4, QtWidgets.QTableWidgetItem("Jam"))
        self.tpelanggan.setHorizontalHeaderItem(
            5, QtWidgets.QTableWidgetItem("Tanggal"))
        self.tpelanggan.setHorizontalHeaderItem(
            6, QtWidgets.QTableWidgetItem("Biaya"))

        self.tadministrator.setColumnCount(4)
        self.tadministrator.setHorizontalHeaderItem(
            0, QtWidgets.QTableWidgetItem("ID"))
        self.tadministrator.setHorizontalHeaderItem(
            1, QtWidgets.QTableWidgetItem("Nama"))
        self.tadministrator.setHorizontalHeaderItem(
            2, QtWidgets.QTableWidgetItem("No Telp"))
        self.tadministrator.setHorizontalHeaderItem(
            3, QtWidgets.QTableWidgetItem("Username"))
        self.tadministrator.setColumnWidth(0, 50)
        self.tadministrator.setColumnWidth(1, 150)

        self.timer = QTimer()
        self.timer.timeout.connect(self.timing)
        self.timer.start(1000)

        self.timing()
        self.koneksi()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADMINISTRATOR"))
        self.header1.setText(_translate(
            "MainWindow", "OPERATOR PAS MASUK PELABUHAN"))
        self.header2.setText(_translate("MainWindow", "UPP KELAS III SAPUDI"))
        self.klogin.setText(_translate("MainWindow", "SUPER ADMIN"))
        self.keterangan.setText(_translate(
            "MainWindow", "HALAMAN ADMINISTRATOR"))
        self.bhapus.setText(_translate("MainWindow", "HAPUS"))
        self.breload.setText(_translate("MainWindow", "RELOAD"))
        self.lnama.setPlaceholderText(
            _translate("MainWindow", "NAMA OPERATOR"))
        self.lnotelp.setPlaceholderText(_translate("MainWindow", "NO TELEPON"))
        self.lusername.setPlaceholderText(_translate("MainWindow", "USERNAME"))
        self.lpassword.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.btambahadmin.setText(_translate("MainWindow", "TAMBAH"))
        self.bhapusadmin.setText(_translate("MainWindow", "HAPUS"))
        self.lidpel.setPlaceholderText(
            _translate("MainWindow", "ID PELANGGAN"))
        self.bdata.setText(_translate("MainWindow", "DATA"))

    def koneksi(self):
        try:
            mydb = mc.connect(host="localhost", user="root", password="",
                              db="db_paspelabuhan")
            self.lketerangan.setText("Berhasil Terkoneksi ke Database")
        except mc.Error as e:
            self.lketerangan.setText("Gagal Terkoneksi ke Database")

    def timing(self):
        time = datetime.now()
        self.showtime = time.strftime(
            "%H : %M : %S" + " WIB" + " / %d - %m - %Y")
        self.waktu.setText(self.showtime)

    def readpelanggan(self):
        mydb = mc.connect(host="localhost", user="root", password="",
                          db="db_paspelabuhan")
        cur = mydb.cursor()
        query = "SELECT * FROM pelanggan"
        cur.execute(query)
        data = cur.fetchall()
        self.tpelanggan.setRowCount(0)

        for row_number, row_data in enumerate(data):
            self.tpelanggan.insertRow(row_number)
            for column_number, data1 in enumerate(row_data):
                self.tpelanggan.setItem(
                    row_number, column_number, QtWidgets.QTableWidgetItem(str(data1)))
        self.readadmin()

    def readadmin(self):
        mydb = mc.connect(host="localhost", user="root", password="",
                          db="db_paspelabuhan")
        cur = mydb.cursor()
        query = "SELECT * FROM admin"
        cur.execute(query)
        data = cur.fetchall()
        self.tadministrator.setRowCount(0)

        for row_number, row_data in enumerate(data):
            self.tadministrator.insertRow(row_number)
            for column_number, data1 in enumerate(row_data):
                self.tadministrator.setItem(
                    row_number, column_number, QtWidgets.QTableWidgetItem(str(data1)))
        self.lketerangan.setText("Data di Reload")

    def tambahadmin(self):
        try:
            mydb = mc.connect(host="localhost", user="root", password="",
                              db="db_paspelabuhan")
            cur = mydb.cursor()
            nama = self.lnama.text()
            username = self.lusername.text()
            no_telp = self.lnotelp.text()
            password = self.lpassword.text()

            query = "INSERT INTO admin (nama, no_telp, username, password) VALUES (%s, %s, %s, %s)"
            value = (nama, no_telp, username, password)

            if (nama == ""):
                self.lketerangan.setText("Nama Operator Harus di isi!!!")
            elif (no_telp == ""):
                self.lketerangan.setText("No Telp Operator Harus di isi!!!")
            elif (username == ""):
                self.lketerangan.setText("Username Operator Harus di isi!!!")
            elif (password == ""):
                self.lketerangan.setText("Password Operator harus di Isi!!!")
            else:
                cur.execute(query, value)
                self.lketerangan.setText("Data Berhasil di Tambahkan")

                # mengkosongkan keterangan
                self.lnama.setText("")
                self.lusername.setText("")
                self.lnotelp.setText("")
                self.lpassword.setText("")

            mydb.commit()

        except mc.Error as e:
            self.lketerangan.setText("Data Gagal di Tambahkan")

    def deletepelanggan(self):
        mydb = mc.connect(host="localhost", user="root", password="",
                          db="db_paspelabuhan")
        cur = mydb.cursor()
        idpel = self.lidpel.text()

        query = "DELETE FROM pelanggan WHERE idpel = %s"
        value = (idpel,)

        try:
            if (idpel == ""):
                self.lketerangan.setText("Id Pelanggan Tidak Boleh Kosong!!")
            else:
                cur.execute(query, value)
                mydb.commit()
                self.lketerangan.setText(
                    "Id Pelanggan = " + idpel + " Dihapus")
                self.lidpel.setText("")
        except:
            self.lketerangan.setText("Gagal Menghapus Data")

    def deleteadmin(self):
        mydb = mc.connect(host="localhost", user="root", password="",
                          db="db_paspelabuhan")
        cur = mydb.cursor()
        username = self.lusername.text()

        query = "DELETE FROM admin WHERE username = %s"
        value = (username,)

        try:
            if (username == ""):
                self.lketerangan.setText("Username Tidak Boleh Kosong!!")
            else:
                cur.execute(query, value)
                mydb.commit()
                self.lketerangan.setText("Admin = " + username + " Dihapus")
                self.lusername.setText("")
        except:
            self.lketerangan.setText("Gagal Menghapus Data")

    def openData(self):
        self.windowData = QtWidgets.QMainWindow()
        self.showWindowData = Ui_DataWindow()
        self.showWindowData.setupUi(self.windowData)
        self.windowData.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_SAdminWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
